### ISSUE TITLE
Material design just draws box instead of icon shape

### ISSUE THREAD

**Issue by hirschenberger** [dioxus-community/dioxus-free-icons#26]
I only get a box displayed instead of the icon.

![image](https://github.com/nissy-dev/dioxus-free-icons/assets/1053180/260b53dd-c424-4cd8-a5a6-581d8acd675d)

Inspecting the SVG shows that there are actually two paths, with a filled box over the icon.

![image](https://github.com/nissy-dev/dioxus-free-icons/assets/1053180/04c46ec6-8092-4fd6-9a3c-f63b25c9d678)

If I delete the first path, the icon is displayed.

![image](https://github.com/nissy-dev/dioxus-free-icons/assets/1053180/49967f49-a6fd-4419-b453-4bf40a562b0a)

**Comment by koenichiwa** [comment]
I want to add something to this, I found that it's not just a second path. Some do, such as `MdEdit`
```html
<svg stroke="currentColor" stroke-width="0" class="" height="20" width="20" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill="black">
    <title></title>
    <path d="M0 0h24v24H0z"></path>
    <path d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z"></path>
</svg>
```
But some even have a literal rectangle, such as `MdAddTask`
```html
<svg stroke="currentColor" stroke-width="0" class="" height="20" width="20" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill="black">
    <title></title>
    <rect height="24" width="24"></rect>
    <path d="M22,5.18L10.59,16.6l-4.24-4.24l1.41-1.41l2.83,2.83l10-10L22,5.18z M12,20c-4.41,0-8-3.59-8-8s3.59-8,8-8 c1.57,0,3.04,0.46,4.28,1.25l1.45-1.45C16.1,2.67,14.13,2,12,2C6.48,2,2,6.48,2,12s4.48,10,10,10c1.73,0,3.36-0.44,4.78-1.22 l-1.5-1.5C14.28,19.74,13.17,20,12,20z M19,15h-3v2h3v3h2v-3h3v-2h-3v-3h-2V15z"></path>
</svg>
```
