### ISSUE TITLE
Future of dioxus-free-icons

### ISSUE THREAD

**Issue by marc2332** [dioxus-community/dioxus-free-icons#27]
Hi!

I am building [Dioxus Community](https://github.com/dioxus-community), a place to develop and maintain projects for Dioxus 🧬.
Are you still developting this project? If you want, we can take care (you can join the org too if you want) 😄 Having the project in the org would make it easier for others to maintain and kee up to date the project when you can't or don't want anymore ❤️.

You would need to transfer the repo over GitHub, so the stars, issues & pull request history is preserved! Also the transfer of the [crate](https://crates.io/crates/dioxus-helmet) would be great. Credits to you will be left on the README too! 

What do you think? :v:

**Comment by nissy-dev** [comment]
@marc2332 Thank you for reaching me!

Your proposal is good for me and building the community is so great! I want to transfer the repository and crate to the community.

**Comment by marc2332** [comment]
> @marc2332 Thank you for reaching me!
> 
> Your proposal is good for me and building the community is so great! I want to transfer the repository and crate to the community.

Awesome!! You can transfer the repo from the settings ([docs](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account)), and the crate can be transferred by just adding a new owner and removing the old one ([docs](https://crates.io/policies#package-ownership)), my crates.io account is [marc2332](https://crates.io/users/marc2332).

Do you also want to join the GitHub organization? 😄

**Comment by nissy-dev** [comment]
I tried to do the transfer, but I got an error related to the permission. I also sent an invitation to you about crate.

<img width="659" alt="SS_ 2023-10-11 9 12 06" src="https://github.com/nissy-dev/dioxus-free-icons/assets/17228098/795b6fde-1877-471c-bcb4-748f97a36707">

**Comment by marc2332** [comment]
> I tried to do the transfer, but I got an error related to the permission. I also sent an invitation to you about crate.
> <img alt="SS_ 2023-10-11 9 12 06" width="659" src="https://user-images.githubusercontent.com/17228098/274101751-795b6fde-1877-471c-bcb4-748f97a36707.png">

I just invited you to the org, it should work after you accept 😄 :v:

**Comment by nissy-dev** [comment]
Thanks! I finished transferring this library to community
