### ISSUE TITLE
bug: Feather Icons weird rendering on dioxus 0.5

### ISSUE THREAD

**Issue by rathod-sahaab** [dioxus-community/dioxus-free-icons#40]
Thanks for the awesome library!! I am facing this issue with icons

![Screenshot from 2024-04-17 04-23-47](https://github.com/dioxus-community/dioxus-free-icons/assets/31929374/63d7769c-7480-4e7d-bf79-30808ea39af4)

Original icons
![image](https://github.com/dioxus-community/dioxus-free-icons/assets/31929374/3e774c2b-8144-4980-95df-8f828a71e122)
![image](https://github.com/dioxus-community/dioxus-free-icons/assets/31929374/95e6d78e-2b88-4d2f-a097-ddabb095f7d4)

`dioxus-free-icons = { version = "0.8.3", features = ["ionicons", "feather"] }
`
and the code
```                   
button {
   Icon { icon: FiFolderPlus }
   "Create folder"
 }
button {
   Icon { icon: FiDelete }
  "Remove Project"
}
```

What am I missing?

**Comment by marc2332** [comment]
I think I broke it because of the inner fill color, will fix it and release a new version asap!

**Comment by marc2332** [comment]
Hey @rathod-sahaab I just opened https://github.com/dioxus-community/dioxus-free-icons/pull/41, it seems to be working, can you give it a try ? 😄
