### ISSUE TITLE
style attribute support

### ISSUE THREAD

**Issue by wooden-worm** [dioxus-community/dioxus-free-icons#53]
I'm trying to use icons with absolute positions - something like `style="top: 20px; left: 30px;"`. Unfortunately `dioxus_free_icons::Icon` does not support custom `style` attribute.

I can work on a PR to add `style` attribute support if this is desired.

**Comment by marc2332** [comment]
> I can work on a PR to add style attribute support if this is desired.
Yeah, feel free! Should be easy I think
