### ISSUE TITLE
`Component<_>` is not implemented for `fn(IconProps<_>) -> Result<VNode, RenderError> {Icon::<_>}`

### ISSUE THREAD

**Issue by markcda** [dioxus-community/dioxus-free-icons#57]
```
00:00:49 [cargo] error[E0277]: `Component<_>` is not implemented for `fn(IconProps<_>) -> Result<VNode, RenderError> {Icon::<_>}`
   --> /home/titoffklim/project/src/components/accordion.rs:94:9
    |
87  | /   rsx! {
88  | |     div {
89  | |       class: "flex",
90  | |       button {
...   |
94  | |         Icon {
    | |         ^^^^ Component
...   |
99  | |     }
100 | |   }
    | |___- required by a bound introduced by this call
    |
    = note: consider using `--verbose` to print the full type name to the console
    = help: the trait `ComponentFunction<_, _>` is not implemented for fn item `fn(IconProps<_>) -> Result<VNode, RenderError> {Icon::<_>}`
    = note: Components are functions in the form `fn() -> Element`, `fn(props: Properties) -> Element`, or `#[component] fn(partial_eq1: u32, partial_eq2: u32) -> Element`.
    = note: You may have forgotten to add `#[component]` to your function to automatically implement the `ComponentFunction` trait.
note: required by a bound in `dioxus::prelude::fc_to_builder`
   --> /home/titoffklim/.cargo/git/checkouts/dioxus-1e619ce595d3799d/e0575b3/packages/core/src/properties.rs:110:36
```

This error shows up on `0.6.0-alpha.4` version, simple adding `#[component]` to `pub fn Icon<T>` isn't working

**Comment by marc2332** [comment]
This is because dioxus-free-icons's dioxus and your dioxus (alpha.4) don't match. Can you try with https://github.com/dioxus-community/dioxus-free-icons/pull/55 ?

**Comment by markcda** [comment]
> Can you try with #55 ?

Yeah, already tried it

```Cargo.toml
dioxus-free-icons = { git = "https://github.com/dioxus-community/dioxus-free-icons.git", branch = "feat/dioxus-0.6", features = ["hero-icons-solid"] }
```

**Comment by marc2332** [comment]
> > Can you try with #55 ?
> 
> Yeah, already tried it
> 
> ```toml
> dioxus-free-icons = { git = "https://github.com/dioxus-community/dioxus-free-icons.git", branch = "feat/dioxus-0.6", features = ["hero-icons-solid"] }
> ```

Try updating with `cargo update`, I updated it to alpha 4 just some minutes ago

**Comment by markcda** [comment]
> > > Can you try with #55 ?
> > 
> > 
> > Yeah, already tried it
> > ```toml
> > dioxus-free-icons = { git = "https://github.com/dioxus-community/dioxus-free-icons.git", branch = "feat/dioxus-0.6", features = ["hero-icons-solid"] }
> > ```
> 
> Try updating with `cargo update`, I updated it to alpha 4 just some minutes ago

I've seen. This is the `dioxus-free-icons/Cargo.toml` that I using:

```Cargo.toml
# monorepo only work when using virtual manifest
# see: https://github.com/rust-lang/cargo/issues/7467#issuecomment-867632379
[workspace]
resolver = "2"
members = [
    "packages/codegen",
    "packages/example",
    "packages/lib",
]

[workspace.dependencies]
dioxus = "0.6.0-alpha.4"

```

**Comment by marc2332** [comment]
But did you run `cargo update`?

**Comment by markcda** [comment]
> But did you run `cargo update`?

Yes, of course.
I mean, I saw your update and sync in a minute. No changes at all. Tell me if you needed an example project to reproduce the error.

**Comment by markcda** [comment]
Well, I just created a project from scratch and everything compiled.

I'm so sorry for wasting your time. Thank for your patience!
